{% set name = "yaqd-gdrive" %}
{% set version = "2020.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5936105a4ce05554696bca64d830af4992c98adac7171105a812805ecf4590ad

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-gdrive = yaqd_gdrive._gdrive:GDrive.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - flit
    - aiohttp
    - yaqd-core >=2020.06.3
  run:
    - python >=3.7
    - aiohttp
    - yaqd-core >=2020.06.3

test:
  imports:
    - yaqd_gdrive
  commands:
    - pip check
    - yaqd-gdrive --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: Daemon interface for writing files to Google Drive
  dev_url: https://gitlab.com/yaq/yaqd-gdrive
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
